language: node_js
env:
  global:
    - TEST_COMMAND=test
matrix:
  include:
    - node_js: 8
    - node_js: 9
    - node_js: 10
    - node_js: 11
    - node_js: node
    - node_js: node
      env: TEST_COMMAND=test:coverage
before_install:
  - npm install -g grunt-cli
script: npm run $TEST_COMMAND
